### ISSUE TITLE
How to create room ?

### ISSUE THREAD

**Issue by lodwig** [totaljs/emptyproject-websocket#1]
Hi Peter, 

I am very interest for your project. can you help me to create a room for this socket ? 
i have the scenario that a client connect to a server in a specific room, a client can connect to multiple room. 
a room is a place to talk with others client and the other room cannot read each others.

i hope you can understand my scenario.

Thank's in advance

**Comment by petersirka** [comment]
Hi @lodwig,
creating a room is very easy:

__Server-side__:

```js
exports.install = function() {
    ROUTE('GET /');
    ROUTE('SOCKET /{room}/', socket);
};

function socket(room) {

    var self = this;
    var messages = 0;
    var interval;

    self.autodestroy(function() {
        clearInterval(interval);
    });

    self.on('open', function(client) {
        // do something
        client.send({ msg: 'Welcome in ' + room });
    });

    self.on('close', function(client) {
        // do something
    });

    self.on('message', function(client, message) {
        console.log('Message:', message);
    });

    // Sends date to all clients
    interval = setInterval(function() {
        messages++;
        self.send({ date: new Date(), messages: messages, room: room });
    }, 1000);
}
```

__Client-side__:

```js
function openroom(room, callback) {
    var ws = new WebSocket(location.origin.replace(/^http/i, 'ws') + '/' + room);
    // ws.onopen = function() {};
    // ws.onclose = function() {};
    // ws.onmessage = function(e) {};
    // ws.send(JSON.stringify({}));
    callback(ws);
}
```

**Comment by lodwig** [comment]
Hi Peter, nice to get in touch with you, i create a controller "dodol.js" with code like this:
```
exports.install = function () {
    ROUTE('GET /{newroom}', home_view);
    ROUTE('SOCKET /{newroom}/', socket);
}
function home_view(newroom) {
    var self = this;
    self.view('index', { inivar: newroom });
}

function socket(newroom) {
    var self = this;
    var messages = 0;
    var interval;

    self.autodestroy(function () {
        clearInterval(interval);
    });

    self.on('open', function (client) {
        // self.send({ messages: "Hi,  Can I Help You?", date: new Date() });
    });

    self.on('close', function (client) {
        console.log("On Close:" + client.ID);
    });

    self.on('message', function (client, message) {
        console.log('Message:', message);
       self.send({ room: newroom, message: messages });
    });

    // Sends date to all clients
    interval = setInterval(function () {
        messages++;
        self.send({ date: new Date(), messages: messages });
    }, 1000);
}
```
and in "views/index.html" i make some changes : 
```
<div data---="websocket__message__url:/@{model.inivar};encoder:false"></div>

<div class="padding">
<div id="servertime"></div>
<div id="messages"></div>
<div class="kirim">
	<input placeholder="Ketikkan Pesan" type="text" name="pesan" id="pesan" />
	<span><button onclick="sendMessages();">kirim</button></span>
</div>
</div>

<script>
function openroom(room, callback) {
	var ws = new WebSocket(location.origin.replace(/^http/i, 'ws') + '/' + room);
	ws.onopen = function () {
		console.log("On Open from client");
	};
	ws.onclose = function () {
		console.log("On Close from client");
	};
	ws.onmessage = function (e) {
		console.log("on message:" + e);
	};
	callback(ws);
}
function sendMessages() {
	openroom("@{model.inivar}", function (socket) {
		socket.send(JSON.stringify({ date: new Date(), message: 'Ini Pesan', room: "@{model.inivar}" }));
	});
}
</script>
```

i got some error when run it :

```
======= 2021-01-29 16:50:04: TypeError: r.compare is not a function TypeError: r.compare is not a function
    at Framework.F.lookup_websocket (/Users/hengkisirait/workspace/others_project/emptyproject-websocket/node_modules/total4/index.js:9279:11)
    at Server.F.$upgrade (/Users/hengkisirait/workspace/others_project/emptyproject-websocket/node_modules/total4/index.js:7770:23)
    at Server.emit (events.js:315:20)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)
```

and on the console client view i got this error on browser:
```
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at http://localhost:8000/asdasd:1:1119
    at openroom (http://localhost:8000/asdasd:1:1040)
    at sendMessages (http://localhost:8000/asdasd:1:1077)
    at HTMLButtonElement.onclick (http://localhost:8000/asdasd:1:725)
```

can you tell me what wrong in my code ?

**Comment by petersirka** [comment]
100x sorry - my mistake. I don't know how, I don't know why... but there was a bug, please reinstall `total4` from NPM :-( ... Thank you.

**Comment by petersirka** [comment]
Let me know if you will have any problem

**Comment by lodwig** [comment]
Thank you it's running on total4 version 0.0.30
